version: "3"

services:
 app:
  build: .
  command: npm run dev
  
  ports:
   - "3000:3000"
  volumes:
   - .:/usr/src/app
   - /usr/src/app/node_modules
  links:
    - mongo
 mongo:
  container_name: mongo
  image: mongo
  ports:
   - "27017:27017"

